### ISSUE TITLE
下载到的adoption数据集结构与yaml文件里的不一样

### ISSUE THREAD

**Issue by NKUShaw** [RyanJJP/CHARMS#1]
kaggle中下载到的数据并没有划分验证集，我该怎么办呢？单纯想把代码跑通

**Comment by RyanJJP** [comment]
你好，kaggle中只能下载到训练集，我们是在整个训练集上划分训练测试验证的

**Comment by NKUShaw** [comment]
感谢回答，请问on_validation_epoch_end这个函数用在哪了？我在尝试在我自己的pytorch框架下把compute_OT和get_mask两个函数引入训练中，但是我并没有在代码找到直接使用它俩的地方。

**Comment by RyanJJP** [comment]
建议参考一下pytorch lightning框架 https://lightning.ai/docs/pytorch/stable/

**Comment by NKUShaw** [comment]
感谢，已经跑通了，这个封装的框架确实有点不熟悉。

**Comment by RyanJJP** [comment]
问题已被决解决
