### ISSUE TITLE
Missing implementations of ContrastiveImagingAndTabularDatasets

### ISSUE THREAD

**Issue by MiHu773** [RyanJJP/CHARMS#2]
Hello! Thank you for sharing your work. I was looking at the implementation of trainers/pretrain.py file and noticed that there is no implementation of classes:
* ContrastiveImagingAndTabularDataset_SUN, 
* ContrastiveImagingAndTabularDataset_Celeba, 
* ContrastiveImagingAndTabularDataset_Pawpularity, 
* ContrastiveImagingAndTabularDataset_Avito, 
* ContrastiveImagingAndTabularDataset_DVM. 

Could you share those classes as well or am I missing something?

**Comment by RyanJJP** [comment]
Hi! Thank you for your attention. These classes can be constructed in the same way as ContrastiveImagingAndTabularDataset_PetFinder. You can refer to ContrastiveImagingAndTabularDataset_PetFinder for more information.
