### ISSUE TITLE
Questions about the classifier in Section 4.3 that enhances the image network’s understanding of tabular attributes.

### ISSUE THREAD

**Issue by HUOUO7** [RyanJJP/CHARMS#3]
Hello, thank you for your excellent work.

I would like to know that in Chapter 4.3 of your paper, you mentioned using existing image feature extractors to train a classifier that maps from image channels to corresponding attributes. So where is the corresponding code for this part?

If you can answer my question, it will be very helpful for me to understand the principles and code of the model more deeply. Thank you!

**Comment by RyanJJP** [comment]
Hi! Thanks for your interest in our work.

In models/CHARMS.py/ImageModelPetFinderWithRTDL/on_validation_epoch_end, we update the mask, which is the transfer matrix in our paper.  In models/CHARMS.py/ImageClassifier/forward function, we use existing image feature extractors to train a classifier that maps from image channels to corresponding attributes. 

If you have any further questions, please let me know. Thank you!

**Comment by RyanJJP** [comment]
Yes.
